---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: lab05-cluster-viewer-binding
  labels:
    app: rbac-lab
subjects:
- kind: ServiceAccount
  name: cluster-viewer
  namespace: lab05-rbac
roleRef:
  kind: ClusterRole
  name: lab05-pod-reader
  apiGroup: rbac.authorization.k8s.io
