---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: developer
  namespace: dev
  labels:
    app: rbac-lab
    role: developer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: viewer
  namespace: dev
  labels:
    app: rbac-lab
    role: viewer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cicd-deployer
  namespace: prod
  labels:
    app: rbac-lab
    role: cicd
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-viewer
  namespace: lab05-rbac
  labels:
    app: rbac-lab
    role: cluster-viewer
