apiVersion: v1
kind: Service
metadata:
  name: web-app-nodeport
  namespace: lab01-basic-deployment
  labels:
    app: web-app
    service-type: nodeport
spec:
  type: NodePort
  selector:
    app: web-app
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
    # nodePort will be automatically assigned in range 30000-32767
    # Or specify explicitly:
    # nodePort: 30080
  sessionAffinity: None
