---
apiVersion: v1
kind: Namespace
metadata:
  name: lab06-privileged
  labels:
    # Privileged: no restrictions
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: v1
kind: Namespace
metadata:
  name: lab06-baseline
  labels:
    # Baseline: prevents known privilege escalations
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/warn: baseline
---
apiVersion: v1
kind: Namespace
metadata:
  name: lab06-restricted
  labels:
    # Restricted: heavily restricted, best practice
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
